spring:
  application:
    name: eureka

server:
  port: ${EUREKA_PORT:8761}

eureka:
  instance:
    hostname: ${EUREKA_HOST:localhost}

  client:
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/
    registry-fetch-interval-seconds: 20
